controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_refresh_token:
    path: /api/token/refresh

api_login_check:
    path: /api/login_check
